[package]
name = "homepage"
version = "0.1.0"
authors = ["yewjung <yewjung@gmail.com>"]
license = "MIT"
edition = "2021"

[dependencies]
ratatui = { version = "0.29.0", default-features = false }
color-eyre = "0.6.3"
ratzilla = "0.1.0"
